services:
  minecraft:
    build:
      context: .
    tty: true
    stdin_open: true
    ports:
      - "${PORT}:25565"
    environment:
      EULA: ${EULA}
      VERSION: ${VERSION}
      DIFFICULTY: ${DIFFICULTY}
      SERVER_NAME: ${SERVER_NAME}
      MAX_PLAYERS: ${MAX_PLAYERS}
      SEED: ${SEED}
      MODE: ${MODE}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
      ONLINE_MODE: ${ONLINE_MODE}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      FORCE_GAMEMODE: ${FORCE_GAMEMODE}
      MOTD: ${MOTD}
    volumes:
      - ./data:/data
    restart: unless-stopped
