services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "${PORT}:25565"
    environment:
      EULA: ${EULA}
      VERSION: ${VERSION}
      DIFFICULTY: ${DIFFICULTY}
      SERVER_NAME: ${SERVER_NAME}
      MAX_PLAYERS: ${MAX_PLAYERS}
      SEED: ${SEED}
      MODE: ${MODE}
    volumes:
      - ./data:/data
    restart: unless-stopped