services:
  minecraft:
    build:
      context: .
    tty: true
    stdin_open: true
    ports:
      - "${PORT}:25565"
      - "24454:24454"
    environment:
      EULA: ${EULA}
      VERSION: ${VERSION}
      MEMORY: ${MEMORY}
      DIFFICULTY: ${DIFFICULTY}
      SERVER_NAME: ${SERVER_NAME}
      MAX_PLAYERS: ${MAX_PLAYERS}
      SEED: ${SEED}
      MODE: ${MODE}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
      ONLINE_MODE: ${ONLINE_MODE}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      FORCE_GAMEMODE: ${FORCE_GAMEMODE}
      MOTD: ${MOTD}
      TYPE: ${TYPE}
      MODS_FILE: ${MODS_FILE}
      REMOVE_OLD_MODS: ${REMOVE_OLD_MODS}
    volumes:
      - ./data:/data
    restart: unless-stopped
