# fly.toml app configuration file generated for minecraft-server-discord-muga on 2024-07-18T12:37:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minecraft-server-discord-muga'
primary_region = 'mia'
kill_timeout = '5m0s'
swap_size_mb = 512

[build]
  dockerfile = 'Dockerfile'

[env]
  DIFFICULTY = 'hard'
  ENABLE_COMMAND_BLOCK = 'false'
  EULA = 'TRUE'
  MEMORY = '1G'
  FORCE_GAMEMODE = 'true'
  MAX_PLAYERS = '10'
  MODE = 'survival'
  ONLINE_MODE = 'false'
  SERVER_NAME = 'Minecraft-Server'
  SPAWN_PROTECTION = '16'
  VERSION = '1.21'
  MOTD = 'El mejor server de Maincra :)'
  TYPE = 'FABRIC'
  MODS_FILE = '/extras/mods.txt'
  PLUGINS_FILE = '/extras/plugins.txt'
  REMOVE_OLD_MODS = 'TRUE'

[[mounts]]
  source = 'minecraft'
  destination = '/data'
  snapshot_retention = 14
  initial_size = 5

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[services.ports]]
    port = 25565

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 25565

  [[services.ports]]
    port = 25565

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpu_kind = 'shared'

